<?php
get_template_part('header');
get_template_part('template-parts/home/section1');
get_template_part('template-parts/home/section2');
get_template_part('template-parts/home/section3');
get_template_part('template-parts/home/section4');
get_template_part('template-parts/home/section5');
get_template_part('template-parts/home/section6');
get_template_part('template-parts/home/footer');